[package]
name = "etcdv3"
version = "0.1.0"
authors = ["The etcdv3 Authors <davidli2010@foxmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "An etcd v3 API client"
repository = "https://github.com/etcdv3/etcdv3.git"
keywords = ["etcd", "v3", "api", "client", "async", "sync"]

[dependencies]
tonic = "0.1"
prost = "0.6"
tokio = { version = "0.2", features = ["rt-core", "stream", "sync", "rt-threaded"] }
futures-core = "0.3"
http = "0.2"

[build-dependencies]
tonic-build = "0.1"
