[package]
name = "etcd-client"
version = "0.6.3"
authors = ["The etcd-client Authors <davidli2010@foxmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "An etcd v3 API client"
repository = "https://github.com/etcdv3/etcd-client.git"
homepage = "https://github.com/etcdv3/etcd-client"
documentation = "https://docs.rs/etcd-client/"
keywords = ["etcd", "v3", "api", "client", "async"]

[features]
tls = ["tonic/tls"]
tls-roots = ["tls", "tonic/tls-roots"]

[dependencies]
tonic = "0.4.1"
prost = "0.7.0"
tokio = "1.4.0"
tokio-stream = "0.1.5"
http = "0.2.3"

[dev-dependencies]
tokio = { version = "1.4.0", features = ["full"] }

[build-dependencies]
tonic-build = { version = "0.4.1", default-features = false, features = ["prost"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
