name: Etcd Client Test
run-name: ${{ github.actor }} is testing out etcd client
on:
  pull_request:
    branches: ["master"]
    paths:
      - 'src/**'
      - 'examples/**'
      - 'proto/**'

jobs:
  regression-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Get latest etcd from docker hub"
      - run: docker --version
      - run: sudo docker pull bitnami/etcd:latest 
      - run: sudo docker network create app-tier --driver bridge
      - run: sudo docker run -d --name Etcd-server --network app-tier --publish 2379:2379 --publish 2380:2380 --env ALLOW_NONE_AUTHENTICATION=yes --env ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379 bitnami/etcd:latest
      - run: sudo apt install -y protobuf-compiler libprotobuf-dev
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: test code style check
        run: cargo clippy
      - name: test etcd client unit
        run: cargo test
      - name: run examples
      - run: cd examples && cargo run --example auth
      - run: cd examples && cargo run --example auth_role
      - run: cd examples && cargo run --example auth_user
      - run: cd examples && cargo run --example cluster
      - run: cd examples && cargo run --example election
      - run: cd examples && cargo run --example kv
      - run: cd examples && cargo run --example lease
      - run: cd examples && cargo run --example lock
      - run: cd examples && cargo run --example maintenance
      - run: cd examples && cargo run --example watch
